language: python

python:
  - "3.9"

cache: pip

install:
  - pip install -U pip setuptools
  - pip install -e .

script:
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls